Repository camaraproject/DeviceStatus, pull requests merged in 2024-07, with the labels that each got.

#178 Delete device-status.yaml has we have now the separate endpoints
  code/API_definitions/device-status.yaml
Labels: Fall24

#179 Switch device structure to optional
  code/API_definitions/device-reachability-status.yaml
  code/API_definitions/device-roaming-status.yaml
Labels: Fall24

#183 `device-reachability-status` & `device-roaming-status`: Alignment of errors with Commonalities
  code/API_definitions/device-reachability-status.yaml
  code/API_definitions/device-roaming-status.yaml
Labels: enhancement, Fall24

#185 Remove `terms of service` and `contact`
  code/API_definitions/device-reachability-status-subscriptions.yaml
  code/API_definitions/device-reachability-status.yaml
  code/API_definitions/device-roaming-status-subscriptions.yaml
  code/API_definitions/device-roaming-status.yaml
Labels: Fall24

#170 Update the subscription models to align on CAMARA commonalities
  code/API_definitions/device-reachability-status-subscriptions.yaml
  code/API_definitions/device-roaming-status-subscriptions.yaml
Labels: enhancement, Fall24

#121 Add termination reason `SUBSCRIPTION_DELETED` when subscription deleted by the user
  code/API_definitions/device-reachability-status-subscriptions.yaml
  code/API_definitions/device-roaming-status-subscriptions.yaml
Labels: enhancement, Fall24

#194 Renamed RequestRoamingStatus to RoamingStatusRequest
  code/API_definitions/device-roaming-status.yaml
Labels: Fall24, RC1

#195 Removing note that the API-scope is limited to 4G and 5G
  README.md
Labels: Fall24, RC1

#193 Subscription-APIs: Alignment of errors with Commonalities
  code/API_definitions/device-reachability-status-subscriptions.yaml
  code/API_definitions/device-roaming-status-subscriptions.yaml
Labels: enhancement, Fall24, RC1
