Repository camaraproject/DeviceStatus, pull requests merged in 2024-04, with the labels that each got.

#129 fix: change INVALID_INPUT for INVALID_ARGUMENT according to guidelines
  code/API_definitions/device-status.yaml
Labels: v0.5.1

#132 MoM-2024-03-27
  documentation/MeetingMinutes/MoM-2024-03-27.md
Labels: subproject management

#131 Update device-status.yaml
  code/API_definitions/device-status.yaml
Labels: v0.6.0

#123 Adding configuration for Github Actions with linting ruleset
  .github/workflows/megalinter.yml
  .github/workflows/spectral_oas_lint.yml
  .spectral.yml
  .yamllint.yaml
  lint_function/camara-language-avoid-telco.js
  lint_function/camara-reserved-words.js
  lint_function/camara-security-no-secrets-in-path-or-query-parameters.js
Labels: v0.6.0

#141 renaming "EventType"-components to be more clear & update component descriptions
  code/API_definitions/device-status.yaml
Labels: v0.6.0

#144 Make '+' mandatory for phoneNumber
  code/API_definitions/device-status.yaml
Labels: v0.6.0
